# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'CocoaAsyncSocket'

target 'Nxs MIdi Controller' do

end

target 'Nxs MIdi ControllerTests' do

end

